### ISSUE TITLE
Implement "subcell" click event

### ISSUE THREAD

**Issue by nbey** [JarvusInnovations/jarvus-aggregrid#1]
- [ ] Clicking on any 'cell' or 'subcell' fires the `cellclick` event.

**Comment by themightychris** [comment]
@nbey please review my comments and the additional commits I made before merging: https://github.com/JarvusInnovations/jarvus-aggregrid/compare/dd738471c02ddebdce65d43bd4765bd78fcc8d44...eeb2716019d977c62b53524065a3ed1c307ee196
